// <auto-generated />
using System;
using AthenaFinance.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace athena_finance_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304092844_AddPriceProvidersTable")]
    partial class AddPriceProvidersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AthenaFinance.Api.Models.EodPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("MarketCapMillions")
                        .HasPrecision(24, 6)
                        .HasColumnType("numeric(24,6)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("SecurityId")
                        .HasColumnType("integer");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SecurityId", "Date")
                        .IsUnique();

                    b.ToTable("EodPrices");
                });

            modelBuilder.Entity("AthenaFinance.Api.Models.PriceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresApiKey")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PriceProviders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "https://finnhub.io/api/v1/",
                            Code = "finnhub",
                            Description = "Real-time & EOD data for US/CAD stocks. Free tier: 60 req/min.",
                            IsActive = true,
                            Name = "Finnhub",
                            Notes = "Best coverage for US/NASDAQ/NYSE. Limited free-tier support for EU/ASIA.",
                            Priority = 1,
                            RequiresApiKey = true
                        },
                        new
                        {
                            Id = 2,
                            BaseUrl = "https://query1.finance.yahoo.com/",
                            Code = "yahoo",
                            Description = "Unofficial API. No key required. Global coverage (EU, ASIA, US).",
                            IsActive = true,
                            Name = "Yahoo Finance",
                            Notes = "Unofficial — no SLA. Symbols use exchange suffixes: MC.PA, SIE.DE, 7203.T, 0700.HK etc.",
                            Priority = 2,
                            RequiresApiKey = false
                        },
                        new
                        {
                            Id = 3,
                            BaseUrl = "https://api.frankfurter.app/",
                            Code = "frankfurter",
                            Description = "Official ECB exchange rates. Free, no key, major currency pairs only.",
                            IsActive = true,
                            Name = "Frankfurter (ECB)",
                            Notes = "Used exclusively for Forex. Only covers ECB-published pairs.",
                            Priority = 3,
                            RequiresApiKey = false
                        },
                        new
                        {
                            Id = 4,
                            BaseUrl = "https://api.polygon.io/",
                            Code = "polygon",
                            Description = "US stock universe bulk snapshots + OHLCV. Free tier: 15-min delayed.",
                            IsActive = true,
                            Name = "Polygon.io",
                            Notes = "Used by UniverseSyncBackgroundService for bulk US EOD snapshots.",
                            Priority = 4,
                            RequiresApiKey = true
                        });
                });

            modelBuilder.Entity("AthenaFinance.Api.Models.Security", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PriceSourceId")
                        .HasColumnType("integer");

                    b.Property<string>("PriceSourceSymbol")
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PriceSourceId");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Securities");
                });

            modelBuilder.Entity("AthenaFinance.Api.Models.WatchlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SecurityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SecurityId");

                    b.ToTable("WatchlistItems");
                });

            modelBuilder.Entity("AthenaFinance.Api.Models.EodPrice", b =>
                {
                    b.HasOne("AthenaFinance.Api.Models.Security", "Security")
                        .WithMany("Prices")
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Security");
                });

            modelBuilder.Entity("AthenaFinance.Api.Models.Security", b =>
                {
                    b.HasOne("AthenaFinance.Api.Models.PriceProvider", "PriceSource")
                        .WithMany("Securities")
                        .HasForeignKey("PriceSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PriceSource");
                });

            modelBuilder.Entity("AthenaFinance.Api.Models.WatchlistItem", b =>
                {
                    b.HasOne("AthenaFinance.Api.Models.Security", "Security")
                        .WithMany("WatchlistItems")
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Security");
                });

            modelBuilder.Entity("AthenaFinance.Api.Models.PriceProvider", b =>
                {
                    b.Navigation("Securities");
                });

            modelBuilder.Entity("AthenaFinance.Api.Models.Security", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("WatchlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
